import Foundation

final class ParticialLocalizationManager {
    let basicKey = "basic.key"
    let multilineKey = "multiline.key"
    let escapedKey = "escaped.key"
    let unicodeKey = "unicode.key"
    let spacesKey = "spaces.key"
    let commentKey = "comment.key"
    let keyWithSpecialChars = "key-with-special/chars&@#"
    let formatKey = "format.key"
    let htmlKey = "html.key"
    let jsonKey = "json.key"
    let emptyKey = "empty.key"
    let emojiKey = "emoji.key"
    let comment1Key = "comment1.key"
    let comment2Key = "comment2.key"
    let multilineCommentKey = "multiline.comment.key"
    let activeKey = "active.key"
    let mixedCommentKey = "mixed.comment.key"
    let chineseSimplifiedKey = "chinese.simplified.key"
    let chineseTraditionalKey = "chinese.traditional.key"
    let japaneseKey = "japanese.key"
    let japaneseMixedKey = "japanese.mixed.key"
    let koreanKey = "korean.key"
    let arabicKey = "arabic.key"
    let arabicMixedKey = "arabic.mixed.key"
    let russianKey = "russian.key"
    let hindiKey = "hindi.key"
    let thaiKey = "thai.key"
    let mixedLanguagesKey = "mixed.languages.key"
//    let numberFormatKey = "number.format.key"
//    let numberFormatDevanagariKey = "number.format.devanagari.key"
}
